apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  externalSecretName: cloudflare-api-token
  refreshTime: 15m
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - cert-manager-system
            - external-dns-system
  externalSecretSpec:
    refreshInterval: 15m
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    target:
      name: cloudflare-api-token-secret
      creationPolicy: Owner
    data:
      - secretKey: api-token
        remoteRef:
          key: ${OP_VAULT_CLOUDFLARE_TOKEN}
