apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-secret-vars
  namespace: flux-system
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: platform-secret-vars
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: ${OP_VAULT_GRAFANA_ADMIN_USER}
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: ${OP_VAULT_GRAFANA_ADMIN_PASSWORD}
    - secretKey: GRAFANA_SMTP_HOST
      remoteRef:
        key: ${OP_VAULT_GRAFANA_SMTP_HOST}
    - secretKey: GRAFANA_SMTP_USER
      remoteRef:
        key: ${OP_VAULT_GRAFANA_SMTP_USER}
    - secretKey: GRAFANA_SMTP_FROM_ADDRESS
      remoteRef:
        key: ${OP_VAULT_GRAFANA_SMTP_FROM_ADDRESS}
    - secretKey: ALERT_EMAIL_TO
      remoteRef:
        key: ${OP_VAULT_ALERT_EMAIL_TO}
    - secretKey: ACME_EMAIL
      remoteRef:
        key: ${OP_VAULT_ACME_EMAIL}
    - secretKey: CLUSTER_ZONE
      remoteRef:
        key: ${OP_VAULT_CLUSTER_ZONE}
    - secretKey: TXT_OWNER_ID
      remoteRef:
        key: ${OP_VAULT_TXT_OWNER_ID}
